version: '3.8'

services:
  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #       - .env
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=matcha
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=matcha
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

networks:
  default:
    external: true
    name: matcha-network
